### ISSUE TITLE
Updating known_good in hal.lua with 2.8

### ISSUE THREAD

**Issue by Patlukat** [coavins/bizhawk-connector#1]
I did a randomizer run with bizhawk 2.8, with your script edited to allow 2.8 and it worked fine for me. From my knowledge lua scripting also didn't really change from 2.7 to 2.8, especially the commands the connector script uses. So it would seem to me that 2.8 should also be added to known_good.

**Comment by coavins** [comment]
Oh good to hear, thanks for confirming that! I'll put it in as soon as I get the chance.

**Comment by coavins** [comment]
Resolved by [8f1c266](https://github.com/coavins/bizhawk-connector/commit/8f1c2668f2e374b1991a579dbf672794cad0a5aa)
